import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/features/main-navigation/ui/MainNavigation";


const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-lato',
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Hanayou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} `}>
        <div className="relative w-screen h-screen overflow-x-hidden ">
          <div className="max-w-[1366px] m-auto">
            <MainNavigation />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
