import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/Header/Header";


const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-lato',
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Hanayou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-bgPrimary text-white max-w-[1366px] m-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
